organism: Bacillus
model_type: ResNetHyperModel
early_stop: 10
cv: 5
seeds: 5
epochs: 300
batch_size: 16
fasta_dir: fasta
weights_dir: weights
best_weights_dir: best_weights
base_results_dir: results
debug: 1
data:
  - k: 3
    encode: fastdna
    slice: [59, 20, 20]
hypermodel:
  execution_per_trial: 3
  hyperband_max_epochs: 30