organism: Bacillus
model_type: HOT_CNN_BACILLUS_02
early_stop: 11
batch_size: 128
epochs: 150
cv: 3
n_samples: 2
fasta_dir: fasta
weights_dir: weights
best_weights_dir: best_weights
base_results_dir: results
debug: 1
data:
  - k: 1
    encode: onehot
    slice: [59, 59, 20]