organism: Bacillus
model_type: HOT_CNN_BACILLUS_02
early_stop: 20
batch_size: 16
epochs: 300
cv: 10
n_samples: 10
fasta_dir: fasta
weights_dir: weights
best_weights_dir: best_weights
base_results_dir: results
debug: 1
data:
  - k: 1
    encode: onehot
    slice: [59, 59, 20]